Switch to mdBook (#134)
* Remove gitbook

* Use mbBook

* Fix error building book (nl)

Error: thread 'main' panicked at 'byte index 1 is not a char boundary; it is inside 'ë' (bytes 0..2) of `ër`', src/libcore/str/mod.rs:2027:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

Replace `spatiëring` with `spaties` to be able to build.

* Remove toc